spring:
  application:
    name: inventory-service
  security:
    oauth2:
      jwt:
        jwk-set-uri: http://192.168.1.102:8080/realms/medron/protocol/openid-connect/certs

  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://192.168.1.102:3305/inventory?createDatabaseIfNotExist=true

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  kafka:
    producer:
      bootstrap-servers: http://192.168.1.102:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: http://192.168.1.102:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}:${random.value}
    prefer-ip-address: true
server:
  port: 0
