
spring:
  application:
    name: invoice-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://192.168.1.102:8080/realms/medron/protocol/openid-connect/certs
  data:
    mongodb:
      database: invoice-db
      uri: mongodb://192.168.1.102:27017

  kafka:
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: http://192.168.1.102:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
server:
  port: 0
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://192.168.1.102:9411/api/v2/spans
